unit upsi_cad2dscripinterface;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 

{ compile-time registration functions }
procedure SIRegister_CAD2DScripInterface(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_CAD2DScripInterface_Routines(S: TPSExec);


implementation


uses
   Graphics
  ,RTTIGrids
  ,PropEdits
  ,ObjectInspector
  ,ComCtrls
  ,CS4BaseTypes
  ,CS4Tasks
  ,CS4Shapes
  ,CADSys4
  ,CS4DXFModule
  ,cImportESSI
  ,CADDocument
  ,camh
  ,applicationh
  ,cad2dscripinterface
  ;
 

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_CAD2DScripInterface(CL: TPSPascalCompiler);
begin
 //CADSys4
 CL.AddTypeS('TRealType', 'single');
 CL.AddTypeS('TPoint2D', 'record X : TRealType; Y : TRealType; W : TRealType; end');
 CL.AddTypeS('TRect2D', 'record FirstEdge : TPoint2D; SecondEdge: TPoint2D; end');
 CL.AddTypeS('TArcDirection', '(adClockwise, adCounterClockwise)');

 CL.AddTypeS('TPenSource', '(psByLayer, psByBlock, psCustom)');
 CL.AddTypeS('TBrushSource', '(bsByLayer, bsByBlock, bsCustom)');
 CL.AddTypeS('TColorSource', '(csByLayer, csByBlock, csCustom)');

 CL.AddTypeS('TCopymode', 'longint');

 CL.AddTypeS('TFrameStartCorner', '(fsLeftTop, fsLeftBottom, fsRightBottom, fsRightTop)');
 CL.AddTypeS('THJustification', '(jhLeft, jhRight, jhCenter)');
 CL.AddTypeS('TVJustification', '(jvTop, jvBottom, jvCenter)');

 //CAM
 CL.AddTypeS('TKerfType', '(ktNone, ktInnerContourCW, ktInnerContourCCW, ktOuterContourCW, ktOuterContourCCW)');

 CL.AddDelphiFunction('function Point2D(X: TRealType; Y: TRealType): TPoint2D');
 CL.AddDelphiFunction('function CAD_Rect2D(var Left, Bottom, Right, Top: TRealType): TRect2D');


 //LazCAD

  CL.AddDelphiFunction('Procedure GetActiveDocument');
  CL.AddDelphiFunction('Procedure CAD_Regen');
  CL.AddDelphiFunction('procedure CAD_Clear');
  CL.AddDelphiFunction('procedure CAD_ZoomToExtentions');

  CL.AddDelphiFunction('function CAD_ImportDXF(AFileName: string): boolean');
  CL.AddDelphiFunction('function CAD_ExportDXF(AFileName: string): boolean');
  CL.AddDelphiFunction('function CAD_ImportESSI(AFileName: string): boolean');

  CL.AddDelphiFunction('Function CAD_DrawLine2D( AID : longint; var P0, P1 : TPoint2D) : integer');
  CL.AddDelphiFunction('Function CAD_DrawEllipticalArc2D( AID : longint; var P0, P1 : TPoint2D; SA, EA : TRealType; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawCircularArc2D( AID : longint; var CP : TPoint2D; R, SA, EA : TRealType; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawCircle2D( AID : longint; var CP : TPoint2D; R, SA : TRealType; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawPolyline2D( AID : longint) : longint');
  CL.AddDelphiFunction('Function CAD_DrawFrame2D( AID : longint; var P0, P1 : TPoint2D; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawPolygon2D( AID : longint; var ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawBSPline2D( AID : longint) : longInt');
  CL.AddDelphiFunction('Function CAD_DrawEllipse2D( AID : longint; var P0, P1 : TPoint2D; ACurvePrecision : word; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawSector2D( AID : longint; var CP : TPoint2D; R, SA, EA : TRealType; ACurvePrecision : word; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawSegment2D( AID : longint; var CP : TPoint2D; R, SA, EA : TRealType; ACurvePrecision : word; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawSymetricSymbol2D( AID : longint; var CP : TPoint2D; R, SA : TRealType; ACurvePrecision : word; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawASymetricSymbol2D( AID : longint; var P0, P1 : TPoint2D; R, SA : TRealType; ACurvePrecision : word; ADirection : TArcDirection) : longint');
  CL.AddDelphiFunction('Function CAD_DrawText2D( AID : longint; var ARect2D : TRect2D; AHeight : TrealType; AStr : String) : longint');
  CL.AddDelphiFunction('Function CAD_DrawJustifiedVectText2D( AID : longint; AFontIndex : word; var ARect2D : TRect2D; AHeight : TrealType; AStr : string) : longint');
  CL.AddDelphiFunction('Function CAD_DrawBitmap2D( AID : longint; var P0, P1 : TPoint2D; AFileName : string) : longInt');
  CL.AddDelphiFunction('Function CAD_Polyline2DAddPoint2D( AIDX : longint; var APoint2D : TPoint2D) : longint');
  CL.AddDelphiFunction('Function CAD_Polygon2DAddPoint2D( AIDX : longint; var APoint2D : TPoint2D) : longint');
  CL.AddDelphiFunction('Function CAD_BSpline2DAddPoint2D( AIDX : longint; var APoint2D : TPoint2D) : longint');
  CL.AddDelphiFunction('Function CAD_GetBrushSource( AID : longint) : TBrushSource');
  CL.AddDelphiFunction('Function CAD_SetBrushSource( AID : longint; AValue : TBrushSource) : boolean');
  CL.AddDelphiFunction('Function CAD_GetBrushColor( AID : longint) : TColor');
  CL.AddDelphiFunction('Function CAD_SetBrushColor( AID : longint; AValue : TColor) : boolean');
  CL.AddDelphiFunction('Function CAD_GetBrushStyle( AID : longint) : TBrushStyle');
  CL.AddDelphiFunction('Function CAD_SetBrushStyle( AID : longint; AValue : TBrushStyle) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjGetClassName( AID : longint) : string');
  CL.AddDelphiFunction('Function CAD_GrObjGetEnabled( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjSetEnabled( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjGetVisible( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjSetVisible( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjGetLayerIndex( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_GrObjSetLayerIndex( AID : longint; AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjGetLayerName( AID : longint) : string');
  CL.AddDelphiFunction('Function CAD_GrObjSetLayerName( AID : longint; AValue : string) : boolean');
  CL.AddDelphiFunction('Function CAD_GrObjGetTag( AID : longint) : integer');
  CL.AddDelphiFunction('Function CAD_GrObjSetTag( AID : longint; AValue : integer) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetAngle( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetBottom( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetBottom( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetLeft( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetLeft( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetRight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetRight( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetTop( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetTop( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetMiddlePoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_Obj2DSetMiddlePoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetMiddlePoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetMiddlePoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetMiddlePoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetMiddlePoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Obj2DGetMiddlePoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Obj2DSetMiddlePoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Prim2DGetPenSource( AID : longint) : TPenSource');
  CL.AddDelphiFunction('Function CAD_Prim2DSetPenSource( AID : longint; AValue : TPenSource) : boolean');
  CL.AddDelphiFunction('Function CAD_Prim2DSetPenColor( AID : integer; AColor : TColor) : boolean');
  CL.AddDelphiFunction('Function CAD_Prim2DGetPenColor( AID : longint) : TColor');
  CL.AddDelphiFunction('Function CAD_Prim2DSetPenWidth( AID : integer; AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_Prim2DGetPenWidth( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_Prim2DSetPenStyle( AID : integer; AValue : TPenStyle) : boolean');
  CL.AddDelphiFunction('Function CAD_Prim2DGetPenStyle( AID : longint) : TPenStyle');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetStartPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetStartPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetStartPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetStartPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetStartPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetStartPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetStartPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetStartPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetEndPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetEndPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetEndPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetEndPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetEndPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetEndPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetEndPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetEndPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetShowDirection( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DSetShowDirection( AID : longint; var AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_SimplePrim2DGetObjectLength( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetEndAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetEndAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetArcAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetArcAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetCenterPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetCenterPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetCenterPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetCenterPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetCenterPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetCenterPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetCenterPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetCenterPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetRadius( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetRadius( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_CircularArc2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_CircularArc2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_ElliArc2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ElliArc2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_ElliArc2DGetEndAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ElliArc2DSetEndAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_ElliArc2DGetArcAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ElliArc2DSetArcAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_ElliArc2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_ElliArc2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_ElliArc2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_ElliArc2DSetDirection( AID : longint; var ADirection : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_ClosedCurve2DGetArea( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ClosedPolyline2DGetArea( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetCenterPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_Circle2DSetCenterPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetCenterPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DSetCenterPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetCenterPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DSetCenterPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetCenterPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DSetCenterPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetRadius( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Circle2DSetRadius( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_Circle2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_Circle2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_Circle2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_Polyline2DGetPointsCount( AID : longint) : integer');
  CL.AddDelphiFunction('Function CAD_Polygon2DGetPointsCount( AID : longint) : integer');
  CL.AddDelphiFunction('Function CAD_BSpline2DGetPointsCount( AID : longint) : integer');
  CL.AddDelphiFunction('Function CAD_Frame2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_Frame2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_Frame2DGetHeight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Frame2DSetHeight( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Frame2DGetWidth( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Frame2DSetWidth( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Frame2DGetStartCorner( AID : longint) : TFrameStartCorner');
  CL.AddDelphiFunction('Function CAD_Frame2DSetStartCorner( AID : longint; var AValue : TFrameStartCorner) : boolean');
  CL.AddDelphiFunction('Function CAD_Ellipse2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_Ellipse2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_Ellipse2DGetHeight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Ellipse2DSetHeight( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Ellipse2DGetWidth( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Ellipse2DSetWidth( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetEndAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetEndAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetArcAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetArcAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetCenterPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_Sector2DSetCenterPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetCenterPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetCenterPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetCenterPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetCenterPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetCenterPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetCenterPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetRadius( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Sector2DSetRadius( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_Sector2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_Sector2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_Sector2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetEndAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetEndAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetArcAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetArcAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetCenterPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_Segment2DSetCenterPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetCenterPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetCenterPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetCenterPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetCenterPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetCenterPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetCenterPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetRadius( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Segment2DSetRadius( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_Segment2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_Segment2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_Segment2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetStartAngle( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetStartAngle( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetCenterPoint2D( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetCenterPoint2D( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetCenterPoint2DX( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetCenterPoint2DX( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetCenterPoint2DY( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetCenterPoint2DY( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetCenterPoint2DW( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetCenterPoint2DW( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetRadius( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetRadius( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DGetCurvePrecision( AID : longint) : word');
  CL.AddDelphiFunction('Function CAD_SymSymbol2DSetCurvePrecision( AID : longint; var AValue : word) : boolean');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DGetDirection( AID : longint) : TArcDirection');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DSetDirection( AID : longint; var AValue : TArcDirection) : boolean');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DGetHeight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DSetHeight( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DGetWidth( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_ASymSymbol2DSetWidth( AID : longint; var AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetText( AID : longint) : string');
  CL.AddDelphiFunction('Function CAD_Text2DSetTex( AID : longint; AValue : string) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetFaceName( AID : longint) : string');
  CL.AddDelphiFunction('Function CAD_Text2DSetFaceName( AID : longint; AValue : string) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetAutoSize( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetAutoSize( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetBold( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetBold( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetUnderline( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetUnderline( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetStrikeout( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetStrikeout( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetItalic( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetItalic( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetDrawBox( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DSetDrawBox( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetHeight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Text2DSetHeight( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetColorSource( AID : longint) : TColorSource');
  CL.AddDelphiFunction('Function CAD_Text2DSetColorSource( AID : longint; AValue : TColorSource) : boolean');
  CL.AddDelphiFunction('Function CAD_Text2DGetColor( AID : longint) : TColor');
  CL.AddDelphiFunction('Function CAD_Text2DSetColor( AID : longint; AValue : TColor) : boolean');
  CL.AddDelphiFunction('Function CAD_Bitmap2DGetScaleFactor( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Bitmap2DSetScaleFactor( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Bitmap2DGetAspectRatio( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_Bitmap2DSetAspectRatio( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_Bitmap2DGetCopyMode( AID : longint) : TCopyMode');
  CL.AddDelphiFunction('Function CAD_Bitmap2DSetCopyMode( AID : longint; AValue : TCopyMode) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetBasePoint( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetBasePoint( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetCharSpace( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetCharSpace( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetDrawBox( AID : longint) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetDrawBox( AID : longint; AValue : boolean) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetHeight( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetHeight( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetHJustification( AID : longint) : THJustification');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetHJustification( AID : longint; AValue : THJustification) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetVJustification( AID : longint) : TVJustification');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetVJustification( AID : longint; AValue : TVJustification) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetInterline( AID : longint) : TRealType');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetInterline( AID : longint; AValue : TRealType) : boolean');
  CL.AddDelphiFunction('Function CAD_JVectText2DGetText( AID : longint) : string');
  CL.AddDelphiFunction('Function CAD_JVectText2DSetText( AID : longint; AValue : string) : boolean');
  CL.AddDelphiFunction('Function CAD_Block2DGetOriginPoint( AID : longint) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_Block2DSetOriginPoint( AID : longint; var APoint2D : TPoint2D) : boolean');
  CL.AddDelphiFunction('Function CAD_Block2DGetSourceName( AID : longint) : string');
  CL.AddDelphiFunction('Procedure CAD_Refresh');
  CL.AddDelphiFunction('Procedure CAD_DeleteObjects');
  CL.AddDelphiFunction('Procedure CAD_ProgressBarReset( AMin, AMax, AStep : integer)');
  CL.AddDelphiFunction('Procedure CAD_ProgressBarStep');
  CL.AddDelphiFunction('Function CAD_GetFiguresCount : integer');
  CL.AddDelphiFunction('Function CAD_GetFigureSP_X( AIndex : integer) : TRealType');
  CL.AddDelphiFunction('Function CAD_GetFigureSP_Y( AIndex : integer) : TRealType');
  CL.AddDelphiFunction('Function CAD_GetFigureEP_X( AIndex : integer) : TRealType');
  CL.AddDelphiFunction('Function CAD_GetFigureEP_Y( AIndex : integer) : TRealType');
  CL.AddDelphiFunction('Function CAD_GetFigureClassName( AIndex : integer) : string');
  CL.AddDelphiFunction('Function CAD_GetFigureKerfInfo( AIndex : integer) : TKerfType');
  CL.AddDelphiFunction('Function CAD_GetFigureProfilePointCount( AIndex : integer) : integer');
  CL.AddDelphiFunction('Function CAD_GetFigureProfilePoint( AFigureIndex, APointIndex : integer) : TPoint2D');
  CL.AddDelphiFunction('Function CAD_GetFigureProfilePointX( AFigureIndex, APointIndex : integer) : TRealType');
  CL.AddDelphiFunction('Function CAD_GetFigureProfilePointY( AFigureIndex, APointIndex : integer) : TRealType');
  CL.AddDelphiFunction('Procedure CAD_ImportDXF');
  CL.AddDelphiFunction('Procedure CAD_ImportESSI');
  CL.AddDelphiFunction('Procedure CAD_ExportDXF');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_CAD2DScripInterface_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@Point2D,                   'Point2D',     cdRegister);
 S.RegisterDelphiFunction(@CAD_Rect2D,                'CAD_Rect2D',     cdRegister);
 S.RegisterDelphiFunction(@Rect2D,                    'Rect2D',     cdRegister);
 S.RegisterDelphiFunction(@GetActiveDocument,         'GetActiveDocument', cdRegister);
 S.RegisterDelphiFunction(@CAD_Regen,                   'CAD_Regen', cdRegister);
 S.RegisterDelphiFunction(@CAD_Clear,                   'CAD_Clear', cdRegister);
 S.RegisterDelphiFunction(@CAD_ZoomToExtentions,        'CAD_ZoomToExtentions', cdRegister);

 S.RegisterDelphiFunction(@CAD_ImportDXF, 'CAD_ImportDXF', cdRegister);
 S.RegisterDelphiFunction(@CAD_ExportDXF, 'CAD_ExportDXF', cdRegister);
 S.RegisterDelphiFunction(@CAD_ImportESSI, 'CAD_ImportESSI', cdRegister);

 S.RegisterDelphiFunction(@CAD_DrawLine2D, 'CAD_DrawLine2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawEllipticalArc2D, 'CAD_DrawEllipticalArc2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawCircularArc2D, 'CAD_DrawCircularArc2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawCircle2D, 'CAD_DrawCircle2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawPolyline2D, 'CAD_DrawPolyline2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawFrame2D, 'CAD_DrawFrame2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawPolygon2D, 'CAD_DrawPolygon2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawBSPline2D, 'CAD_DrawBSPline2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawEllipse2D, 'CAD_DrawEllipse2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawSector2D, 'CAD_DrawSector2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawSegment2D, 'CAD_DrawSegment2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawSymetricSymbol2D, 'CAD_DrawSymetricSymbol2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawASymetricSymbol2D, 'CAD_DrawASymetricSymbol2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawText2D, 'CAD_DrawText2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawJustifiedVectText2D, 'CAD_DrawJustifiedVectText2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_DrawBitmap2D, 'CAD_DrawBitmap2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Polyline2DAddPoint2D, 'CAD_Polyline2DAddPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Polygon2DAddPoint2D, 'CAD_Polygon2DAddPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_BSpline2DAddPoint2D, 'CAD_BSpline2DAddPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetBrushSource, 'CAD_GetBrushSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_SetBrushSource, 'CAD_SetBrushSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetBrushColor, 'CAD_GetBrushColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_SetBrushColor, 'CAD_SetBrushColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetBrushStyle, 'CAD_GetBrushStyle', cdRegister);
 S.RegisterDelphiFunction(@CAD_SetBrushStyle, 'CAD_SetBrushStyle', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetClassName, 'CAD_GrObjGetClassName', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetEnabled, 'CAD_GrObjGetEnabled', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjSetEnabled, 'CAD_GrObjSetEnabled', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetVisible, 'CAD_GrObjGetVisible', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjSetVisible, 'CAD_GrObjSetVisible', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetLayerIndex, 'CAD_GrObjGetLayerIndex', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjSetLayerIndex, 'CAD_GrObjSetLayerIndex', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetLayerName, 'CAD_GrObjGetLayerName', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjSetLayerName, 'CAD_GrObjSetLayerName', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjGetTag, 'CAD_GrObjGetTag', cdRegister);
 S.RegisterDelphiFunction(@CAD_GrObjSetTag, 'CAD_GrObjSetTag', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetAngle, 'CAD_Obj2DGetAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetAngle, 'CAD_Obj2DSetAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetBottom, 'CAD_Obj2DGetBottom', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetBottom, 'CAD_Obj2DSetBottom', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetLeft, 'CAD_Obj2DGetLeft', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetLeft, 'CAD_Obj2DSetLeft', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetRight, 'CAD_Obj2DGetRight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetRight, 'CAD_Obj2DSetRight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetTop, 'CAD_Obj2DGetTop', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetTop, 'CAD_Obj2DSetTop', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetMiddlePoint2D, 'CAD_Obj2DGetMiddlePoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetMiddlePoint2D, 'CAD_Obj2DSetMiddlePoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetMiddlePoint2DX, 'CAD_Obj2DGetMiddlePoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetMiddlePoint2DX, 'CAD_Obj2DSetMiddlePoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetMiddlePoint2DY, 'CAD_Obj2DGetMiddlePoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetMiddlePoint2DY, 'CAD_Obj2DSetMiddlePoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DGetMiddlePoint2DW, 'CAD_Obj2DGetMiddlePoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Obj2DSetMiddlePoint2DW, 'CAD_Obj2DSetMiddlePoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DGetPenSource, 'CAD_Prim2DGetPenSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DSetPenSource, 'CAD_Prim2DSetPenSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DSetPenColor, 'CAD_Prim2DSetPenColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DGetPenColor, 'CAD_Prim2DGetPenColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DSetPenWidth, 'CAD_Prim2DSetPenWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DGetPenWidth, 'CAD_Prim2DGetPenWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DSetPenStyle, 'CAD_Prim2DSetPenStyle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Prim2DGetPenStyle, 'CAD_Prim2DGetPenStyle', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetStartPoint2D, 'CAD_SimplePrim2DGetStartPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetStartPoint2D, 'CAD_SimplePrim2DSetStartPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetStartPoint2DX, 'CAD_SimplePrim2DGetStartPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetStartPoint2DX, 'CAD_SimplePrim2DSetStartPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetStartPoint2DY, 'CAD_SimplePrim2DGetStartPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetStartPoint2DY, 'CAD_SimplePrim2DSetStartPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetStartPoint2DW, 'CAD_SimplePrim2DGetStartPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetStartPoint2DW, 'CAD_SimplePrim2DSetStartPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetEndPoint2D, 'CAD_SimplePrim2DGetEndPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetEndPoint2D, 'CAD_SimplePrim2DSetEndPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetEndPoint2DX, 'CAD_SimplePrim2DGetEndPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetEndPoint2DX, 'CAD_SimplePrim2DSetEndPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetEndPoint2DY, 'CAD_SimplePrim2DGetEndPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetEndPoint2DY, 'CAD_SimplePrim2DSetEndPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetEndPoint2DW, 'CAD_SimplePrim2DGetEndPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetEndPoint2DW, 'CAD_SimplePrim2DSetEndPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetShowDirection, 'CAD_SimplePrim2DGetShowDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DSetShowDirection, 'CAD_SimplePrim2DSetShowDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_SimplePrim2DGetObjectLength, 'CAD_SimplePrim2DGetObjectLength', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetStartAngle, 'CAD_CircularArc2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetStartAngle, 'CAD_CircularArc2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetEndAngle, 'CAD_CircularArc2DGetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetEndAngle, 'CAD_CircularArc2DSetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetArcAngle, 'CAD_CircularArc2DGetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetArcAngle, 'CAD_CircularArc2DSetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetCenterPoint2D, 'CAD_CircularArc2DGetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetCenterPoint2D, 'CAD_CircularArc2DSetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetCenterPoint2DX, 'CAD_CircularArc2DGetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetCenterPoint2DX, 'CAD_CircularArc2DSetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetCenterPoint2DY, 'CAD_CircularArc2DGetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetCenterPoint2DY, 'CAD_CircularArc2DSetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetCenterPoint2DW, 'CAD_CircularArc2DGetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetCenterPoint2DW, 'CAD_CircularArc2DSetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetRadius, 'CAD_CircularArc2DGetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetRadius, 'CAD_CircularArc2DSetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetDirection, 'CAD_CircularArc2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetDirection, 'CAD_CircularArc2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DGetCurvePrecision, 'CAD_CircularArc2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_CircularArc2DSetCurvePrecision, 'CAD_CircularArc2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DGetStartAngle, 'CAD_ElliArc2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DSetStartAngle, 'CAD_ElliArc2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DGetEndAngle, 'CAD_ElliArc2DGetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DSetEndAngle, 'CAD_ElliArc2DSetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DGetArcAngle, 'CAD_ElliArc2DGetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DSetArcAngle, 'CAD_ElliArc2DSetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DGetCurvePrecision, 'CAD_ElliArc2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DSetCurvePrecision, 'CAD_ElliArc2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DGetDirection, 'CAD_ElliArc2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_ElliArc2DSetDirection, 'CAD_ElliArc2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_ClosedCurve2DGetArea, 'CAD_ClosedCurve2DGetArea', cdRegister);
 S.RegisterDelphiFunction(@CAD_ClosedPolyline2DGetArea, 'CAD_ClosedPolyline2DGetArea', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetStartAngle, 'CAD_Circle2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetStartAngle, 'CAD_Circle2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetCenterPoint2D, 'CAD_Circle2DGetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetCenterPoint2D, 'CAD_Circle2DSetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetCenterPoint2DX, 'CAD_Circle2DGetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetCenterPoint2DX, 'CAD_Circle2DSetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetCenterPoint2DY, 'CAD_Circle2DGetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetCenterPoint2DY, 'CAD_Circle2DSetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetCenterPoint2DW, 'CAD_Circle2DGetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetCenterPoint2DW, 'CAD_Circle2DSetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetRadius, 'CAD_Circle2DGetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetRadius, 'CAD_Circle2DSetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetDirection, 'CAD_Circle2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetDirection, 'CAD_Circle2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DGetCurvePrecision, 'CAD_Circle2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_Circle2DSetCurvePrecision, 'CAD_Circle2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_Polyline2DGetPointsCount, 'CAD_Polyline2DGetPointsCount', cdRegister);
 S.RegisterDelphiFunction(@CAD_Polygon2DGetPointsCount, 'CAD_Polygon2DGetPointsCount', cdRegister);
 S.RegisterDelphiFunction(@CAD_BSpline2DGetPointsCount, 'CAD_BSpline2DGetPointsCount', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DGetDirection, 'CAD_Frame2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DSetDirection, 'CAD_Frame2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DGetHeight, 'CAD_Frame2DGetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DSetHeight, 'CAD_Frame2DSetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DGetWidth, 'CAD_Frame2DGetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DSetWidth, 'CAD_Frame2DSetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DGetStartCorner, 'CAD_Frame2DGetStartCorner', cdRegister);
 S.RegisterDelphiFunction(@CAD_Frame2DSetStartCorner, 'CAD_Frame2DSetStartCorner', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DGetDirection, 'CAD_Ellipse2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DSetDirection, 'CAD_Ellipse2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DGetHeight, 'CAD_Ellipse2DGetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DSetHeight, 'CAD_Ellipse2DSetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DGetWidth, 'CAD_Ellipse2DGetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Ellipse2DSetWidth, 'CAD_Ellipse2DSetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetStartAngle, 'CAD_Sector2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetStartAngle, 'CAD_Sector2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetEndAngle, 'CAD_Sector2DGetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetEndAngle, 'CAD_Sector2DSetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetArcAngle, 'CAD_Sector2DGetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetArcAngle, 'CAD_Sector2DSetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetCenterPoint2D, 'CAD_Sector2DGetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetCenterPoint2D, 'CAD_Sector2DSetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetCenterPoint2DX, 'CAD_Sector2DGetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetCenterPoint2DX, 'CAD_Sector2DSetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetCenterPoint2DY, 'CAD_Sector2DGetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetCenterPoint2DY, 'CAD_Sector2DSetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetCenterPoint2DW, 'CAD_Sector2DGetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetCenterPoint2DW, 'CAD_Sector2DSetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetRadius, 'CAD_Sector2DGetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetRadius, 'CAD_Sector2DSetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetDirection, 'CAD_Sector2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetDirection, 'CAD_Sector2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DGetCurvePrecision, 'CAD_Sector2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_Sector2DSetCurvePrecision, 'CAD_Sector2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetStartAngle, 'CAD_Segment2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetStartAngle, 'CAD_Segment2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetEndAngle, 'CAD_Segment2DGetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetEndAngle, 'CAD_Segment2DSetEndAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetArcAngle, 'CAD_Segment2DGetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetArcAngle, 'CAD_Segment2DSetArcAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetCenterPoint2D, 'CAD_Segment2DGetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetCenterPoint2D, 'CAD_Segment2DSetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetCenterPoint2DX, 'CAD_Segment2DGetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetCenterPoint2DX, 'CAD_Segment2DSetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetCenterPoint2DY, 'CAD_Segment2DGetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetCenterPoint2DY, 'CAD_Segment2DSetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetCenterPoint2DW, 'CAD_Segment2DGetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetCenterPoint2DW, 'CAD_Segment2DSetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetRadius, 'CAD_Segment2DGetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetRadius, 'CAD_Segment2DSetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetDirection, 'CAD_Segment2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetDirection, 'CAD_Segment2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DGetCurvePrecision, 'CAD_Segment2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_Segment2DSetCurvePrecision, 'CAD_Segment2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetStartAngle, 'CAD_SymSymbol2DGetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetStartAngle, 'CAD_SymSymbol2DSetStartAngle', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetCenterPoint2D, 'CAD_SymSymbol2DGetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetCenterPoint2D, 'CAD_SymSymbol2DSetCenterPoint2D', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetCenterPoint2DX, 'CAD_SymSymbol2DGetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetCenterPoint2DX, 'CAD_SymSymbol2DSetCenterPoint2DX', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetCenterPoint2DY, 'CAD_SymSymbol2DGetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetCenterPoint2DY, 'CAD_SymSymbol2DSetCenterPoint2DY', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetCenterPoint2DW, 'CAD_SymSymbol2DGetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetCenterPoint2DW, 'CAD_SymSymbol2DSetCenterPoint2DW', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetRadius, 'CAD_SymSymbol2DGetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetRadius, 'CAD_SymSymbol2DSetRadius', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetDirection, 'CAD_SymSymbol2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetDirection, 'CAD_SymSymbol2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DGetCurvePrecision, 'CAD_SymSymbol2DGetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_SymSymbol2DSetCurvePrecision, 'CAD_SymSymbol2DSetCurvePrecision', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DGetDirection, 'CAD_ASymSymbol2DGetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DSetDirection, 'CAD_ASymSymbol2DSetDirection', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DGetHeight, 'CAD_ASymSymbol2DGetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DSetHeight, 'CAD_ASymSymbol2DSetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DGetWidth, 'CAD_ASymSymbol2DGetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_ASymSymbol2DSetWidth, 'CAD_ASymSymbol2DSetWidth', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetText, 'CAD_Text2DGetText', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetTex, 'CAD_Text2DSetTex', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetFaceName, 'CAD_Text2DGetFaceName', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetFaceName, 'CAD_Text2DSetFaceName', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetAutoSize, 'CAD_Text2DGetAutoSize', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetAutoSize, 'CAD_Text2DSetAutoSize', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetBold, 'CAD_Text2DGetBold', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetBold, 'CAD_Text2DSetBold', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetUnderline, 'CAD_Text2DGetUnderline', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetUnderline, 'CAD_Text2DSetUnderline', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetStrikeout, 'CAD_Text2DGetStrikeout', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetStrikeout, 'CAD_Text2DSetStrikeout', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetItalic, 'CAD_Text2DGetItalic', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetItalic, 'CAD_Text2DSetItalic', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetDrawBox, 'CAD_Text2DGetDrawBox', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetDrawBox, 'CAD_Text2DSetDrawBox', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetHeight, 'CAD_Text2DGetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetHeight, 'CAD_Text2DSetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetColorSource, 'CAD_Text2DGetColorSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetColorSource, 'CAD_Text2DSetColorSource', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DGetColor, 'CAD_Text2DGetColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Text2DSetColor, 'CAD_Text2DSetColor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DGetScaleFactor, 'CAD_Bitmap2DGetScaleFactor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DSetScaleFactor, 'CAD_Bitmap2DSetScaleFactor', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DGetAspectRatio, 'CAD_Bitmap2DGetAspectRatio', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DSetAspectRatio, 'CAD_Bitmap2DSetAspectRatio', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DGetCopyMode, 'CAD_Bitmap2DGetCopyMode', cdRegister);
 S.RegisterDelphiFunction(@CAD_Bitmap2DSetCopyMode, 'CAD_Bitmap2DSetCopyMode', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetBasePoint, 'CAD_JVectText2DGetBasePoint', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetBasePoint, 'CAD_JVectText2DSetBasePoint', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetCharSpace, 'CAD_JVectText2DGetCharSpace', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetCharSpace, 'CAD_JVectText2DSetCharSpace', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetDrawBox, 'CAD_JVectText2DGetDrawBox', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetDrawBox, 'CAD_JVectText2DSetDrawBox', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetHeight, 'CAD_JVectText2DGetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetHeight, 'CAD_JVectText2DSetHeight', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetHJustification, 'CAD_JVectText2DGetHJustification', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetHJustification, 'CAD_JVectText2DSetHJustification', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetVJustification, 'CAD_JVectText2DGetVJustification', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetVJustification, 'CAD_JVectText2DSetVJustification', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetInterline, 'CAD_JVectText2DGetInterline', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetInterline, 'CAD_JVectText2DSetInterline', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DGetText, 'CAD_JVectText2DGetText', cdRegister);
 S.RegisterDelphiFunction(@CAD_JVectText2DSetText, 'CAD_JVectText2DSetText', cdRegister);
 S.RegisterDelphiFunction(@CAD_Block2DGetOriginPoint, 'CAD_Block2DGetOriginPoint', cdRegister);
 S.RegisterDelphiFunction(@CAD_Block2DSetOriginPoint, 'CAD_Block2DSetOriginPoint', cdRegister);
 S.RegisterDelphiFunction(@CAD_Block2DGetSourceName, 'CAD_Block2DGetSourceName', cdRegister);
 S.RegisterDelphiFunction(@CAD_Refresh, 'CAD_Refresh', cdRegister);
 S.RegisterDelphiFunction(@CAD_DeleteObjects, 'CAD_DeleteObjects', cdRegister);
 S.RegisterDelphiFunction(@CAD_ProgressBarReset, 'CAD_ProgressBarReset', cdRegister);
 S.RegisterDelphiFunction(@CAD_ProgressBarStep, 'CAD_ProgressBarStep', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFiguresCount, 'CAD_GetFiguresCount', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureSP_X, 'CAD_GetFigureSP_X', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureSP_Y, 'CAD_GetFigureSP_Y', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureEP_X, 'CAD_GetFigureEP_X', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureEP_Y, 'CAD_GetFigureEP_Y', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureClassName, 'CAD_GetFigureClassName', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureKerfInfo, 'CAD_GetFigureKerfInfo', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureProfilePointCount, 'CAD_GetFigureProfilePointCount', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureProfilePoint, 'CAD_GetFigureProfilePoint', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureProfilePointX, 'CAD_GetFigureProfilePointX', cdRegister);
 S.RegisterDelphiFunction(@CAD_GetFigureProfilePointY, 'CAD_GetFigureProfilePointY', cdRegister);
 S.RegisterDelphiFunction(@CAD_ImportDXF, 'CAD_ImportDXF', cdRegister);
 S.RegisterDelphiFunction(@CAD_ImportESSI, 'CAD_ImportESSI', cdRegister);
 S.RegisterDelphiFunction(@CAD_ExportDXF, 'CAD_ExportDXF', cdRegister);
end;

 
end.
