unit FormCodeGenerator;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, StdCtrls;

type
  // Formular-Modell: erbt direkt von TForm
  TFormModel = class(TForm)
  private
    FEventMap: TStringList; // EventName -> HandlerName
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;

    // Event hinzufügen
    procedure AddEvent(AComponent: TComponent; const EventName, HandlerName: string);

    // Code erzeugen
    procedure GenerateFormCode(Code: TStringList);

    property EventMap: TStringList read FEventMap;
  end;

implementation

{ TFormModel }

constructor TFormModel.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  FEventMap := TStringList.Create;
  FEventMap.Sorted := False;
end;

destructor TFormModel.Destroy;
begin
  FEventMap.Free;
  inherited Destroy;
end;

// Event hinzufügen
procedure TFormModel.AddEvent(AComponent: TComponent; const EventName, HandlerName: string);
var
  Key: string;
begin
  // Key = ComponentName.EventName
  Key := AComponent.Name + '.' + EventName;
  FEventMap.Values[Key] := HandlerName;
end;

// Prüfen, ob Prozedur existiert
function ContainsProcedure(Code: TStringList; const ProcName: string): Boolean;
var
  i: Integer;
begin
  Result := False;
  for i := 0 to Code.Count - 1 do
    if Pos('procedure ' + ProcName, Code[i]) = 1 then
    begin
      Result := True;
      Exit;
    end;
end;

// Event-Handler erzeugen
procedure GenerateEventHandler(const HandlerName: string; Code: TStringList);
begin
  if not ContainsProcedure(Code, HandlerName) then
  begin
    Code.Add('');
    Code.Add('procedure ' + HandlerName + '(Sender: TObject);');
    Code.Add('begin');
    Code.Add('  // TODO: implement');
    Code.Add('end;');
    Code.Add('');
  end;
end;

// Komponenten-Code erzeugen
procedure GenerateComponentCode(AComp: TComponent; Code: TStringList);
var
  i: Integer;
begin
  if AComp.Name = '' then Exit; // Skip unnamed

  Code.Add(AComp.Name + ' := ' + AComp.ClassName + '.Create(Self);');
  if AComp is TWinControl then
    Code.Add(AComp.Name + '.Parent := Self;');

  // Properties: Left, Top, Width, Height, Caption (falls vorhanden)
  if AComp is TControl then
  begin
    Code.Add(AComp.Name + '.Left := ' + IntToStr(TControl(AComp).Left) + ';');
    Code.Add(AComp.Name + '.Top := ' + IntToStr(TControl(AComp).Top) + ';');
    Code.Add(AComp.Name + '.Width := ' + IntToStr(TControl(AComp).Width) + ';');
    Code.Add(AComp.Name + '.Height := ' + IntToStr(TControl(AComp).Height) + ';');
  end;

  if AComp is TLabel then
    Code.Add(AComp.Name + '.Caption := ''' + TLabel(AComp).Caption + ''';')
  else if AComp is TButton then
    Code.Add(AComp.Name + '.Caption := ''' + TButton(AComp).Caption + ''';');
end;

// Gesamten Formular-Code generieren
procedure TFormModel.GenerateFormCode(Code: TStringList);
var
  i: Integer;
  Comp: TComponent;
  Key, HandlerName: string;
begin
  Code.Clear;
  Code.Add('// <auto-generated>');

  // Alle Components iterieren
  for i := 0 to ComponentCount - 1 do
  begin
    Comp := Components[i];
    GenerateComponentCode(Comp, Code);

    // Event-Handler aus Map erzeugen
    // Key = ComponentName.EventName
    FEventMap.Sort; // optional
    for Key in FEventMap do
      if Pos(Comp.Name + '.', Key) = 1 then
      begin
        HandlerName := FEventMap.Values[Key];
        GenerateEventHandler(HandlerName, Code);
      end;
  end;

  Code.Add('// </auto-generated>');
  Code.Add('');
  Code.Add('// <user-code>');
  Code.Add('// Hier kann der User eigenen Code schreiben');
  Code.Add('// </user-code>');
  Code.Add('');
end;

end.
